# Generated by Django 6.0.1 on 2026-01-21 14:06

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skilltrack_challenges', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='challengesubmission',
            unique_together={('user', 'challenge')},
        ),
    ]
