# Generated by Django 6.0.1 on 2026-01-13 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skill_exchange', '0002_skill_skillrequest_delete_skillexchange'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='description',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='skillrequest',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='skillrequest',
            name='requester',
            field=models.CharField(max_length=100),
        ),
    ]
