# Generated by Django 6.0.1 on 2026-01-13 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skill_exchange', '0004_skillrequest_created_at_alter_skillrequest_requester'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skillrequest',
            old_name='requester',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='skillrequest',
            name='message',
        ),
        migrations.AddField(
            model_name='skill',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
