# Generated by Django 6.0.1 on 2026-01-13 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skill_exchange', '0005_rename_requester_skillrequest_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='description',
        ),
        migrations.RemoveField(
            model_name='skillrequest',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='skillrequest',
            name='skill',
        ),
        migrations.AddField(
            model_name='skillrequest',
            name='description',
            field=models.TextField(default='No description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='skillrequest',
            name='skill_name',
            field=models.CharField(default='No description', max_length=100),
            preserve_default=False,
        ),
    ]
